/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.producto;

import logica.Producto;
import presentacion.Producto_TableModel;

/**
 *
 * @author Ivan
 */
public class Producto_View extends javax.swing.JDialog implements java.util.Observer {

    /**
     * Creates new form View
     */
    public Producto_View(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        this.setLocation(100, 100);
        this.getContentPane().setBackground(new java.awt.Color(204, 255, 204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Titulo_Registro = new javax.swing.JLabel();
        Label_Detalle = new javax.swing.JLabel();
        Textfield_Detalle = new javax.swing.JTextField();
        Textfield_Unidad = new javax.swing.JTextField();
        Label_Unidad = new javax.swing.JLabel();
        Label_Codigo = new javax.swing.JLabel();
        Textfield_Codigo = new javax.swing.JTextField();
        Label_Precio = new javax.swing.JLabel();
        Textfield_Precio = new javax.swing.JTextField();
        Button_Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Productos = new javax.swing.JTable();
        Label_Buscar = new javax.swing.JLabel();
        Textfield_Buscar = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 255, 204));

        Titulo_Registro.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        Titulo_Registro.setText("Registro de producto");

        Label_Detalle.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Label_Detalle.setText("Detalle:");

        Textfield_Detalle.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Textfield_Detalle.setName(""); // NOI18N
        Textfield_Detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_DetalleActionPerformed(evt);
            }
        });

        Textfield_Unidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Textfield_Unidad.setName(""); // NOI18N
        Textfield_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_UnidadActionPerformed(evt);
            }
        });

        Label_Unidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Label_Unidad.setText("Tipo de unidad:");

        Label_Codigo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Label_Codigo.setText("Código:");

        Textfield_Codigo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Textfield_Codigo.setName(""); // NOI18N
        Textfield_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_CodigoActionPerformed(evt);
            }
        });

        Label_Precio.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Label_Precio.setText("Precio unitario:");

        Textfield_Precio.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Textfield_Precio.setName(""); // NOI18N
        Textfield_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_PrecioActionPerformed(evt);
            }
        });

        Button_Agregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_Agregar.setText("Agregar");
        Button_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Button_AgregarMousePressed(evt);
            }
        });

        Table_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(Table_Productos);

        Label_Buscar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Label_Buscar.setText("Buscar:");

        Textfield_Buscar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        Textfield_Buscar.setName(""); // NOI18N
        Textfield_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(Label_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Textfield_Codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(Textfield_Detalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textfield_Unidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textfield_Precio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(Button_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Titulo_Registro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Label_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Textfield_Buscar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Textfield_Detalle)
                            .addComponent(Label_Detalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Textfield_Unidad)
                            .addComponent(Label_Unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Textfield_Codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Textfield_Precio))
                        .addGap(27, 27, 27)
                        .addComponent(Button_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Textfield_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {                                        
       if( Textfield_Detalle.getText().isEmpty() || Textfield_Codigo.getText().isEmpty() /*|| Textfield_Precio.getText().isEmpty()*/) return; //
       Producto producto = new Producto();
       producto.setDetalle(Textfield_Detalle.getText());
       producto.setCodigo(Textfield_Codigo.getText());
       //producto.setPrecio_unitario(Textfield_Precio.getText());                                                                            //
       control.agregar(producto);
    }                                       

    private void filtroBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Producto filtro= new Producto();
        filtro.setDetalle(Textfield_Buscar.getText());
        control.buscar(filtro);
    }                                            
    
    private void listaMouseClicked(java.awt.event.MouseEvent evt) {                                   
        if(evt.getClickCount()==2){
            control.seleccionar(Table_Productos.getSelectedRow());
        }
    }
    
    private void Textfield_DetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_DetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_DetalleActionPerformed

    private void Textfield_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_UnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_UnidadActionPerformed

    private void Textfield_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_CodigoActionPerformed

    private void Textfield_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_PrecioActionPerformed

    private void Button_AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_AgregarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_AgregarMousePressed

    private void Textfield_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agregar;
    private javax.swing.JLabel Label_Buscar;
    private javax.swing.JLabel Label_Codigo;
    private javax.swing.JLabel Label_Detalle;
    private javax.swing.JLabel Label_Precio;
    private javax.swing.JLabel Label_Unidad;
    private javax.swing.JTable Table_Productos;
    private javax.swing.JTextField Textfield_Buscar;
    private javax.swing.JTextField Textfield_Codigo;
    private javax.swing.JTextField Textfield_Detalle;
    private javax.swing.JTextField Textfield_Precio;
    private javax.swing.JTextField Textfield_Unidad;
    private javax.swing.JLabel Titulo_Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    Producto_Control control;
    Producto_Modelo modelo;
    
    public void setControl(Producto_Control control){
        this.control =control;
    }

    public Producto_Control getControl() {
        return control;
    }
    
    public void setModelo(Producto_Modelo modelo){
        this.modelo = modelo;
         modelo.addObserver(this);
    }

    public Producto_Modelo getModelo() {
        return modelo;
    }

    
   public void update(java.util.Observable updatedModel,Object parametros){
       Producto current = modelo.getCurrent();
       Textfield_Detalle.setText(current.getDetalle());
       Textfield_Codigo.setText(current.getCodigo());
       //Textfield_Precio.setText(current.getPrecio_unitario());
       Table_Productos.setModel(new Producto_TableModel(modelo.getLista()));
   }
}
