/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.aplicacion;
/**
 *
 * @author Ivan
 */
public class Aplicacion_View extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Creates new form View
     */
    public Aplicacion_View() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eleccion = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Producto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Producto.setText("Producto");
        Eleccion.add(jMenu_Producto);
        jMenu_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Producto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ProductoMouseClicked
        this.control.productoShow();
    }//GEN-LAST:event_jMenu_ProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Eleccion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Producto;
    // End of variables declaration//GEN-END:variables

    Aplicacion_Control control;
    Aplicacion_Modelo modelo;
    
    public void setControl(Aplicacion_Control control){
        this.control = control;
    }

    public Aplicacion_Control getControl() {
        return control;
    }
    
    public void setModelo(Aplicacion_Modelo modelo){
        this.modelo = modelo;
         modelo.addObserver(this);
    }

    public Aplicacion_Modelo getModelo() {
        return modelo;
    }
    
    public void update(java.util.Observable updatedModel,Object parametros){
   }
}
